image: node:12

stages:
    - test
    - deploy

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

run-unit-test:
  stage: test
  variables:
    CYPRESS_INSTALL_BINARY: 0
  cache:
    paths:
      - node_modules/
      - .npm
  script:
    - npm install
    - npm run test:unit:ci
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit:
        - junit.xml

run-integration-test:
  image: cypress/browsers:node12.19.0-chrome86-ff82
  stage: test
  only:
    - merge_requests
  variables:
    npm_config_cache: "$CI_PROJECT_DIR/.npm"
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  cache:
    paths:
      - node_modules/
      - .npm
      - cache/Cypress
  script:
    - npm ci
    - npm run test:integration:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit-integration*.xml

pages:
  stage: deploy
  script:
    - cd site/
    - npm install
    - npm run export
    - mv site/__sapper__/export public 
  artifacts:
    paths:
      - public
  cache:
    paths:
      - site/node_modules/
  only:
  - master

.renovate:
  variables:
    RENOVATE_GIT_AUTHOR: "${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>"
    RENOVATE_DRY_RUN: "false"
    RENOVATE_LOG_LEVEL: "info"
  image:
    name: renovate/renovate
    entrypoint: [""]
  script:
    - >
      node /usr/src/app/dist/renovate.js
      --platform "gitlab"
      --endpoint "${CI_API_V4_URL}"
      --git-author "${RENOVATE_GIT_AUTHOR}"
      --dry-run "${RENOVATE_DRY_RUN}"
      --log-level "${RENOVATE_LOG_LEVEL}"
      "${CI_PROJECT_PATH}"
  only:
    - master
    - schedules

Renovate:
  extends: .renovate


# the below doesn't work with absolute links so disable for now
# pages:preview:
#   stage: deploy
#   only:
#     - merge_requests
#   script:
#     - cd site/
#     - npm install
#     - npm run export
#   artifacts:
#     paths:
#       - site/__sapper__/export
#   cache:
#     paths:
#       - site/node_modules/
#   environment:
#     name: preview/${CI_COMMIT_REF_NAME}
#     url: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/site/__sapper__/export/index.html